// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4f7pFMElMdeJNJpyDJn5V5jLq2eA5Sbw',
    appId: '1:1013520523003:web:a9aa047069562159219a5e',
    messagingSenderId: '1013520523003',
    projectId: 'book-vere',
    authDomain: 'book-vere.firebaseapp.com',
    storageBucket: 'book-vere.appspot.com',
    measurementId: 'G-FMT9TEQ5JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ68iBXyKMj3OVFfqj2Htw1pWjTCWSaag',
    appId: '1:1013520523003:android:c758696720c16a52219a5e',
    messagingSenderId: '1013520523003',
    projectId: 'book-vere',
    storageBucket: 'book-vere.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyaVhV0mvVqgl7r1IHSvAAbbmr7imSW0I',
    appId: '1:1013520523003:ios:bab640084518eeb1219a5e',
    messagingSenderId: '1013520523003',
    projectId: 'book-vere',
    storageBucket: 'book-vere.appspot.com',
    iosBundleId: 'com.example.isdfinal',
  );
}
